### ISSUE TITLE
Code Tidy: @JsonTypeName on API Command objects duplicates command names

### ISSUE THREAD

**Issue by amorton** [stargate/data-api#1592]
noticed when doing a review we have code like 

```
@JsonTypeName("dropIndex")
public record DropIndexCommand(
```

And we now have the CommandName enum, so we could do `CommandName.DROP_INDEX.getApiName()` 

this ticket is to update the `@JsonTypeName` for all commands: collections, keyspaces, tables etc .

**Comment by tatu-at-datastax** [comment]
I looked into this, but unfortunately this cannot be done the way things are, because values for Annotation properties must be proper static constants. So, although it is possible to refer to Enum constants for Enum-valued Annotation properties, like hypothetical:

    @MyAnnotation(commandEnum = Command.CommandName.AlterTable)

we can NOT, unfortunately, use

    @JsonTypeName(Command.CommandName.AlterTable.getApiName())

(or, if it was public, field `apiName`).

We would need to add true (`static`) constants for names to refer to, like

    public final static String COMMAND_NAME_ALTER_TABLE = "alterTable"

to do this. This might be doable so will play with the idea a bit.

**Comment by tatu-at-datastax** [comment]
@amorton Created minimal PoC pr (#1645) to show how this could be done, but wanted to confirm this makes sense (original approach is not possible with Java annotations, AFAIK).
